# Generated by Django 3.2.7 on 2021-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('dx', models.IntegerField()),
                ('y', models.IntegerField()),
                ('dy', models.IntegerField()),
            ],
        ),
    ]
