# Generated by Django 3.2.7 on 2021-09-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binarize_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('g', models.IntegerField()),
                ('r', models.IntegerField()),
                ('k', models.IntegerField()),
            ],
        ),
    ]
